---
title: "Next.jsでのエラーハンドリングを考える"
emoji: "🙌"
type: "tech" # tech: 技術記事 / idea: アイデア
topics: ["typescript", "nextjs"]
published: false
---

## Next.js で error を throw するとどうなるか

https://zenn.dev/nus3/scraps/3069a458562eca#comment-72ecff69ed2928

## React の Error Boundary とは

[公式のドキュメント](https://ja.reactjs.org/docs/error-boundaries.html)

- 子コンポーネントのレンダリングエラーを catch して代わりのコンポーネントをレンダリングしてくれる
- class コンポーネントでの実装
  - functional コンポーネントで実装できるライブラリはある(star 数少なめ)
- イベントハンドラのエラーは catch しない

### サンプル実装

```tsx
class ErrorBoundary extends Component<Props, State> {
  public state: State = {
    hasError: false,
  };

  public static getDerivedStateFromError(_: Error): State {
    // Update state so the next render will show the fallback UI.
    return { hasError: true };
  }

  public componentDidCatch(error: Error, errorInfo: ErrorInfo): void {
    console.error("Uncaught error:", error, errorInfo);
  }

  public render(): JSX.Element | ReactNode {
    if (this.state.hasError) {
      return <h1>やべべべ コンポーネントのエラーが起きちゃったよ</h1>;
    }

    return this.props.children;
  }
}
```

```tsx:_app.tsx
const MyApp: NextPage<AppProps> = ({ Component, pageProps }: AppProps) => {

  return (
    <ErrorBoundary>
      <Component {...pageProps} />
    </ErrorBoundary>
  )
}
```

#### ErrorBoundary が表示されるパターン

まぁこんなことはないけども
子コンポーネントが error を throw した時

```tsx
const TestErrorPage: NextPage = () => {
  throw new Error("コンポーネントエラーだよ");

  return (
    <div style={{ padding: "30px" }}>
      <h1>errorの動作確認</h1>
      <button type="button" onClick={handleError}>
        確認
      </button>
    </div>
  );
};
```

ts で実装されているはずなので基本的にはレンダリングでのエラーは throw されないはずだが
**api のレスポンスの型が想定されていないものになっている場合など**可能性はある
例 : 配列を返してくれるはずが string になっている(この場合`Array.prototype.map()`など配列想定のメソッドでエラーになる)

#### ErrorBoundary が表示されないパターン

イベントハンドラ内でエラーを throw した時

```tsx
const TestErrorPage: NextPage = () => {
  const handleError = () => {
    throw new Error("テスト");
  };

  return (
    <div style={{ padding: "30px" }}>
      <h1>errorの動作確認</h1>
      <button type="button" onClick={handleError}>
        確認
      </button>
    </div>
  );
};
```

確認ボタンを押しても console にエラーが出力されるだけ

## Next.js のカスタムエラーページ

[公式のドキュメント](https://nextjs.org/docs/advanced-features/custom-error-page#404-page)

- Next.js の`_error.tsx`が ErrorBoundary の代わりをしてくれそう
- 404.tsx は別途作った方が良さそう
- getInitialProps で page が load されるときのハンドリングが定義できる

### サンプル実装

```tsx:_error.tsx
type ErrorProps = {
  statusCode: number
}

const Error: NextPage<ErrorProps> = ({ statusCode }: ErrorProps) => {
  return (
    <p>
      {statusCode
        ? `An error ${statusCode} occurred on server`
        : 'An error occurred on client'}
    </p>
  )
}

Error.getInitialProps = ({ res, err }: NextPageContext) => {
  const statusCode = res ? res.statusCode : err ? err.statusCode : 404
  return { statusCode }
}
```

## まとめ

- Error Boundary で拾ってくれるエラーは `pages/_error.tsx` も拾ってくれそうなので Next のエラーハンドリングに寄せるで良さそう
- イベントハンドラ内のエラーは別途方針を決める必要がある(例: axios で Error 履いたら特定のダイアログを表示するなど)
